[theme]
base                     = "dark"
backgroundColor          = "#0e0e0f"
secondaryBackgroundColor = "#1a1a1b"
textColor                = "#e8e6e0"
font                     = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false